### ISSUE TITLE
Not working without SSL certificate

### ISSUE THREAD

**Issue by SventB** [thieleundklose/autotranslate#12]
In my local DEV environment, saving the site configuration is not working, I get an error:

in \typo3conf\ext\autotranslate\Resources\Private\Deeplcom\DeeplPhp\src\HttpClient.php line 212
```
#60 DeepL\ConnectionException

SSL certificate problem: unable to get local issuer certificate
```

I have no SSL certificate here.

But seems to be a problem of DeepL PHP library.

**Comment by mikezimmer-tuk** [comment]
Hi Sven, could you check if this bug is still present? I Checked it without an ssl certificate, but al seems to be fine.

Best regards, Mike

**Comment by mikezimmer-tuk** [comment]
@SventB I've just checked the problem. It is not possible to call the DeepL API without https. A call without https ends in a 301 redirect. I would close the issue because of this.
