### ISSUE TITLE
Problem with content elements in EXT:news

### ISSUE THREAD

**Issue by SventB** [thieleundklose/autotranslate#15]
There's bug with TYPO3 v10 and feature "Content elements" of EXT:news:

![image](https://github.com/thieleundklose/autotranslate/assets/2690489/492a80f8-2dc2-4420-ba5c-480dca193a91)

When adding a new content element here, an error is thrown:

` Core: Exception handler (WEB): Uncaught TYPO3 Exception: Argument 1 passed to TYPO3\CMS\Core\Site\SiteFinder::getSiteByPageId() must be of the type int, string given, called in /typo3conf/ext/autotranslate/Classes/UserFunction/FormEngine/AutotranslateLanguagesItems.php on line 65 `

This can be fixed here (https://github.com/thieleundklose/autotranslate/blob/main/Classes/UserFunction/FormEngine/AutotranslateLanguagesItems.php#L47) by

`$sitePid = (int)$row['pid'];`

**Comment by mikezimmer-tuk** [comment]
Thanks for reporting, already fixed in v1.0.2
